// src/components/AppFooter.tsx
import React from "react";
import config from "../developer.json";

const AppFooter: React.FC = () => {
  return (
    <footer className="w-full hidden lg:flex justify-between items-center px-6 py-4 border-t border-[#1E2D3D]">
      <div className="flex items-center space-x-6">
        <span className="text-menu-text font-fira_retina text-sm">
          find me in:
        </span>
        <div className="flex space-x-3">
          {config.contacts.social.github && (
            <a
              href={`${config.contacts.social.github.url}${config.contacts.social.github.user}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-menu-text hover:text-white"
            >
              <img
                src="/icons/social/github.svg"
                alt="GitHub"
                className="w-5 h-5"
              />
            </a>
          )}
          {config.contacts.social.linkedin && (
            <a
              href={`${config.contacts.social.linkedin.url}${config.contacts.social.linkedin.user}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-menu-text hover:text-white"
            >
              <img
                src="/icons/social/linkedin.svg"
                alt="LinkedIn"
                className="w-5 h-5"
              />
            </a>
          )}
        </div>
      </div>
      <div className="text-menu-text font-fira_retina text-sm">
        @{config.contacts.social.github?.user}
      </div>
    </footer>
  );
};

export default AppFooter;

// components/AppFooter.vue
<template>
    <footer class='flex md:justify-between border-top text-menu-text font-fira_retina'>

        <!-- social icons -->
        <div class="w-full flex justify-between md:justify-start">
            <span id="social-title" class="h-full flex justify-center items-center border-right px-5">
                find me in:
            </span>
            <div id="social-icons" class="flex">
                
                <NuxtLink :to="social.linkedin.url + social.linkedin.user" target="_blank" class="flex justify-center items-center">
                    <img src="/icons/social/linkedin.svg" alt="linkedin"/>
                </NuxtLink>
                <NuxtLink :to="social.whatsapp.url + social.whatsapp.user" target="_blank" class="flex justify-center items-center">
                    <img src="/icons/social/whatsapp.svg" alt="whatsapp"/>
                </NuxtLink>
            </div>
        </div>

        <!-- github user -->
        <NuxtLink :to="social.github.url + social.github.user" target="_blank" class="hidden md:flex items-center px-5 border-left">
            @{{ social.github.user }}
            <img src="/icons/social/github.svg" alt="github"/>
        </NuxtLink>

    </footer>
</template>

<script setup>
import config from '~/developer.json';

const social = ref(config.contacts.social);
</script>

<script>
export default {
    name: 'AppFooter',
}
</script>

<style>

footer {
    height: 40px;
    min-height: 40px;
    font-size: 13px;
}

footer a:hover {
    background-color: #1e2d3d74;
}

#social-icons > a {
    border-right: 1px solid #1E2D3D;
    height: 100%;
    width: 50px;
 }

#social-icons > a > img {
    width: 1.25rem; /* 20px */
    height: 1.25rem; /* 20px */
    margin: auto;
    opacity: 0.4;
}

footer > a > img {
    width: 1.25rem; /* 20px */
    height: 1.25rem; /* 20px */
    margin-left: 0.5rem; /* 8px */
  }

#social-icons > a:hover img {
    opacity: 1;
}

@media (max-width: 768px) {

    #social-title {
        border-right: none;
    }

    #social-icons > a {
        border-right: none;
        border-left: 1px solid #1E2D3D;
    }

    #social-icons > a > img {
        width: 1.5rem; /* 20px */
        height: 1.5rem; /* 20px */
  }
}

</style>
