// src/components/AppHeader.tsx
import React from "react";
import { Link, useLocation } from "react-router-dom";
import config from "../developer.json";

const AppHeader: React.FC = () => {
  const location = useLocation();

  const isActive = (path: string) => {
    return location.pathname === path;
  };

  return (
    <header id="navbar" className="w-full hidden lg:flex flex-col">
      <nav className="w-full flex justify-between border-bot">
        <div className="flex">
          <Link
            id="nav-logo"
            to="/"
            className="text-menu-text font-fira_retina px-6 h-full flex items-center border-right hover:bg-[#1e2d3d74] hover:text-white"
          >
            {config.logo_name}
          </Link>

          <Link
            id="nav-link"
            to="/"
            className={`text-menu-text font-fira_retina px-6 h-full flex items-center border-right hover:bg-[#1e2d3d74] hover:text-white ${
              isActive("/") ? "border-b-2 border-[#FEA55F] text-white" : ""
            }`}
          >
            _hello
          </Link>

          <Link
            id="nav-link"
            to="/about-me"
            className={`text-menu-text font-fira_retina px-6 h-full flex items-center border-right hover:bg-[#1e2d3d74] hover:text-white ${
              isActive("/about-me")
                ? "border-b-2 border-[#FEA55F] text-white"
                : ""
            }`}
          >
            _about-me
          </Link>

          <Link
            id="nav-link"
            to="/projects"
            className={`text-menu-text font-fira_retina px-6 h-full flex items-center border-right hover:bg-[#1e2d3d74] hover:text-white ${
              isActive("/projects")
                ? "border-b-2 border-[#FEA55F] text-white"
                : ""
            }`}
          >
            _projects
          </Link>
        </div>

        <Link
          id="nav-link-contact"
          to="/contact-me"
          className={`text-menu-text font-fira_retina px-6 h-full flex items-center border-left hover:bg-[#1e2d3d74] hover:text-white ${
            isActive("/contact-me")
              ? "border-b-2 border-[#FEA55F] text-white"
              : ""
          }`}
        >
          _contact-me
        </Link>
      </nav>
    </header>
  );
};

export default AppHeader;

// components/AppHeader.vue
<template>
    <header id="navbar" class="w-full hidden lg:flex flex-col">
      <nav class="w-full flex justify-between border-bot">
          
          <div class="flex">  
            <NuxtLink id="nav-logo" to="/">
              {{ config.logo_name }}
            </NuxtLink>

            <NuxtLink id="nav-link" to="/" :class="{ active: isActive('/') }">
              _hello
            </NuxtLink>
  
            <NuxtLink id="nav-link" to="/about-me" :class="{ active: isActive('/about-me') }">
              _about-me
            </NuxtLink>
  
            <NuxtLink id="nav-link" to="/projects" :class="{ active: isActive('/projects') }">
              _projects
            </NuxtLink>
          </div>

          <NuxtLink id="nav-link-contact" to="/contact-me" :class="{ active: isActive('/contact-me')}">
            _contact-me
          </NuxtLink>
      
      </nav>

    </header>

</template>

<script setup>
// import GithubCorner from './GithubCorner.vue';
import config from '~/developer.json';

const isActive = (route) => {
  return route === route;
}

</script>

<script>
export default {
  name: 'AppHeader',
};
</script>

<style>

#nav-link {
  border-right: 1px solid #1E2D3D;
  @apply text-menu-text font-fira_retina px-6 h-full flex items-center;
}

#nav-link-contact {
  border-left: 1px solid #1E2D3D;
  @apply text-menu-text font-fira_retina px-6 h-full flex items-center;
}

#nav-link:hover, #nav-link-contact:hover {
  background-color: #1e2d3d74;
  color: white;
}

#nav-logo {
  border-right: 1px solid #1E2D3D;
  @apply text-menu-text font-fira_retina px-6 h-full flex items-center;
}

#nav-logo:hover {
  background-color: #1e2d3d74;
  color: white;
}

#nav-link.router-link-active, #nav-link-contact.router-link-active {
  border-bottom: 2px solid #FEA55F;
  color: white;
}

#nav-logo.router-link-active {
  border-right: 1px solid #1E2D3D;
  border-bottom: none;
  @apply text-menu-text;
}

#navbar > nav {
  height: 45px;
  font-size: 13px;
}

</style>
