// src/pages/ContactMe.tsx
import React from "react";
import config from "../developer.json";

const ContactMe: React.FC = () => {
  return (
    <main className="page">
      <div id="mobile-page-title">
        <h2>_contact-me</h2>
      </div>

      <div className="flex flex-col lg:flex-row h-full w-full">
        <div className="flex-1 p-8">
          <h1 className="text-3xl font-fira_bold text-white mb-6">
            Contact Me
          </h1>

          <div className="space-y-6">
            <div>
              <h2 className="text-xl font-fira_bold text-white mb-4">
                Get in Touch
              </h2>
              <p className="text-menu-text font-fira_retina">
                I'm always open to discussing new opportunities, collaborating
                on projects, or just having a chat about technology.
              </p>
            </div>

            <div>
              <h3 className="text-lg font-fira_bold text-white mb-3">
                Contact Information
              </h3>
              <div className="space-y-2">
                <div className="flex items-center">
                  <img
                    src="/icons/email.svg"
                    alt="Email"
                    className="w-4 h-4 mr-3"
                  />
                  <span className="text-menu-text font-fira_retina">
                    {config.contacts.direct.sources.email}
                  </span>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-lg font-fira_bold text-white mb-3">
                Social Media
              </h3>
              <div className="flex space-x-4">
                {config.contacts.social.github && (
                  <a
                    href={`${config.contacts.social.github.url}${config.contacts.social.github.user}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center text-menu-text hover:text-white"
                  >
                    <img
                      src="/icons/social/github.svg"
                      alt="GitHub"
                      className="w-5 h-5 mr-2"
                    />
                    GitHub
                  </a>
                )}
                {config.contacts.social.linkedin && (
                  <a
                    href={`${config.contacts.social.linkedin.url}${config.contacts.social.linkedin.user}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center text-menu-text hover:text-white"
                  >
                    <img
                      src="/icons/social/linkedin.svg"
                      alt="LinkedIn"
                      className="w-5 h-5 mr-2"
                    />
                    LinkedIn
                  </a>
                )}
              </div>
            </div>
          </div>
        </div>

        <div className="flex-1 p-8">
          <div className="bg-blue-background border border-[#1E2D3D] rounded-lg p-6">
            <h3 className="text-white font-fira_bold text-lg mb-4">
              Contact Form
            </h3>
            <p className="text-menu-text font-fira_retina text-sm">
              Contact form functionality coming soon...
            </p>
          </div>
        </div>
      </div>
    </main>
  );
};

export default ContactMe;

// pages/contact-me.vue
<template>
    <main id="contact-me" class="page">

        <div id="mobile-page-title">
            <h2>_contact-me</h2>
        </div>

        <div id="page-menu" class="w-full h-full flex flex-col border-right">

            <!-- contacts -->
            <div id="contacts" class="submenu">
                <div class="title" @click="open('contacts')">
                    <img class="arrow" src="/icons/arrow.svg" alt="">
                    <h3>
                        contacts
                    </h3>
                </div>
                <div id="links">
                    <div v-for="(source, key) in contact.direct.sources" :key="key" class="link">
                        <img :src="'/icons/' + key + '.svg'" alt="">
                        <a v-html="source" href="/" class="font-fira_retina text-menu-text hover:text-white"></a>
                    </div>
                </div>
            </div>

            <!-- find me also in
            <div id="find-me-in" class="submenu border-top">
                <div class="title" @click="open('find-me-in')">
                    <img class="arrow" src="/icons/arrow.svg" alt="">
                    <h3>
                        find-me-also-in
                    </h3>
                </div>
                <div id="links">
                    <div v-for="(source, key) in contact.find_me_also_in.sources" :key="key" class="link">
                        <img src="/icons/link.svg" alt="">
                        <a :href="source.url + source.user" class="font-fira_retina text-menu-text hover:text-white" target="_blank">{{ source.title }}</a>
                    </div>
                </div>
            </div> -->

        </div>
            
        <div class="flex flex-col w-full">

        <!-- windows tab -->
        <div class="tab-height w-full hidden lg:flex border-right border-bot items-center">

                <div class="flex items-center border-right h-full">
                    <p class="font-fira_regular text-menu-text text-sm px-3">contacts</p>
                    <img src="/icons/close.svg" alt="" class="m-3">
                </div>

            </div>

            <!-- main -->
            <div class="flex lg:grid lg:grid-cols-2 h-full w-full">
        
                <div id="left" class="h-full w-full flex flex-col border-right items-center">
                    
                    <ContactForm />

                </div>

                <div id="right" class="h-full w-full hidden lg:flex">
                    
                    <div class="form-content">
                        <FormContentCode />
                    </div>
                    <!-- scroll bar -->
                    <div id="scroll-bar" class="h-full border-left flex justify-center py-1">
                        <div id="scroll"></div>
                    </div>
                
                </div>
            </div>

        </div>
    </main>
</template>

<script>
import DevConfig from '~/developer.json';
export default {
    setup() {
        return {
            contact: DevConfig.contacts,
        }
    },
    methods: {
        open(elementId) {
            const element = document.getElementById(elementId);
            const arrow = element.querySelector('.arrow');
            const links = element.querySelector('#links');

            if (links.style.display === 'block') {
                links.style.display = 'none';
                arrow.style.transform = 'rotate(0deg)';
            } else {
                links.style.display = 'block';
                arrow.style.transform = 'rotate(90deg)';
            }
        }
    },
    mounted(){
        /**
         * * Close all submenus
         * ! This is a temporary solution.
         * ! This is needed because when the page is loaded, height style on #links are not applied.
         */
        const links = document.getElementsByClassName('submenu');
        for (let i = 0; i < links.length; i++) {
            if(window.innerWidth > 1024){ 
                links[i].querySelector("#links").style.display = "block";
                links[i].querySelector(".arrow").style.transform = "rotate(90deg)";
            } else {
                links[i].querySelector("#links").style.display = "none";
            }
        }
    },
}
</script>

<style>

.arrow {
    transition: 0.1s;
    margin-right: 10px;
    width: 9px;
    height: 9px;
}

.submenu {
    display: flex;
    flex-direction: column;
}

.submenu .title h3 {
    @apply font-fira_regular;
    color: white;
    font-size: 16px;
}

.link {
    display: flex;
    align-items: center;
    padding: 4px 25px;
}

.link img {
    width: 16px;
    height: 16px;
    margin-right: 10px;
}

#links {
    padding: 10px 0px;
}

.form-content {
    padding: 75px 50px 0px 75px;
    width: 100%;
    height: 100%;
    overflow-y: auto;
    font-size: 15px;
}
@media (min-width: 1024px) {
    
    .submenu .title {
        display: flex;
        align-items: center;
        border-bottom: 1px solid #1E2D3D;
        padding: 0px 25px;
        height: 35px;
        padding: 0px 25px;
    }
    .submenu .title:hover {
        cursor: pointer;
    }
    .submenu .title h3 {
        font-size: 14px;
    }
}

</style>
